### ISSUE TITLE
Update gh-pages branch please!

### ISSUE THREAD

**Issue by Guard13007** [pico-8/awesome-PICO-8#30]
All the activity here is on the master branch instead of `gh-pages`. The result is that while there has been a lot added, the actual site is sparse and massively out of date.

I would suggest updating the gh-pages branch and maybe removing master altogether, making the default branch gh-pages.

Edit: I just noticed that the gh-pages branch is entirely separate from master. Anything in it not in master needs to be copied over manually before it can be removed and a new gh-pages created from master.. Or, manually update it from master, and remove master.

**Comment by felipebueno** [comment]
Thanks for pointing that out, @Guard13007. I completely forgot about the ```gh-pages``` branch.

I'm (was) using the Github's Automatic Page Generator and I'd regenerate it manually everytime we updated the README.md file. I's been quite a while since I last updated it.

I'll leave this issue open and look into fix that later. And thanks for the suggestion as well.

**Comment by Guard13007** [comment]
What's the status on this?

**Comment by felipebueno** [comment]
Not good :(

I haven't had time to work on personal and community projects for a while and when I have the time I don't have the motivation to do so =/

If you wanna help with that I could add you as a commiter to the repo. What do you think?

**Comment by tobiasvl** [comment]
Still nothing happening here?

**Comment by h404bi** [comment]
I have updated it on https://pico-8.github.io/awesome-PICO-8/.
Didn't notice that there is @pico8dev. That's cool that the PICO-8 Discord server creates that org! I would like to invite all your guys to the @pico-8 organization if you are willing to. Or should I donate the organization out?

**Comment by felipebueno** [comment]
Hi, @tobiasvl and @h404bi!

I think I'm goint to transfer this repo to the @pico-8 organization. Maybe we could centralize all community driven pico projects there.

And the name @pico-8 is way cooler than @pico8dev :laughing: Just kiding...

What do you guys, think of that?

**Comment by tobiasvl** [comment]
Oh lol, I don't think we knew about that one either :) We haven't started using ours yet really, as you can see, so let me run it by the other peeps!

**Comment by tobiasvl** [comment]
@h404bi If you'd like to invite us, we'd love to combine forces 👍

**Comment by h404bi** [comment]
@tobiasvl 
Of course! Have sent the invitation to you. Don't know if there are any other PICO-8 enthusiasts who are willing to join in the organization. If so, you can leave your comment in https://github.com/pico-8/Joinin/issues/1 or just mention me with my id @h404bi in the pico-8 discord server. I'll send the invitation soon! 🆒

**Comment by felipebueno** [comment]
@h404bi Can you delete the awesome-PICO-8 fork so I can transfer the repo's ownership to the @pico-8 organization, please?

**Comment by h404bi** [comment]
@felipebueno just deleted.

@tobiasvl I have sent an invitation to @2Tie , but it seems 2Tie doesn't have time to accept it.

**Comment by felipebueno** [comment]
@h404bi Done! :)

**Comment by h404bi** [comment]
So the next step, let's `fix` this issue, update the site by deleting `gh-pages` branch and setting `master` branch as the GitHub Pages source.

**Comment by h404bi** [comment]
Now it's the latest one!
