### ISSUE TITLE
Lack of "PICO-8. The Basics" videotutorial series link

### ISSUE THREAD

**Issue by JasonNumberThirteen** [pico-8/awesome-PICO-8#57]
Excuse me, I'd like to notify that my course called "_PICO-8. Podstawy_" (in English it's called "_PICO-8. The Basics_") doesn't exist on "_Tutorials_" list. Any chance to put it there? Here's the link to the first chapter as a proof:

https://www.youtube.com/watch?v=4r2x1OKazqA

**Comment by felipebueno** [comment]
Hi, @JasonNumberThirteen!

Feel free to add it there and send us a Pull Request with the changes :smiley:

**Comment by JasonNumberThirteen** [comment]
How can I do it?

**Comment by merwok** [comment]
Follow this link to edit the README file: https://github.com/pico-8/awesome-PICO-8/edit/master/README.md

**Comment by JasonNumberThirteen** [comment]
Thank you.
