### ISSUE TITLE
Add some carts!

### ISSUE THREAD

**Issue by jedahan** [pico-8/awesome-PICO-8#7]
I don't have pico-8 on this machine, but when I remember/find some interesting carts I will add them here

**Comment by felipebueno** [comment]
Nice, thanks, @jedahan ! :smile:

**Comment by felipebueno** [comment]
Hey @jedahan are you still going to add that carts? 

I'm not rushing you or anything... I just think it'd be a good addition to the repository :smile: :+1:

**Comment by booyaa** [comment]
How about adding the winners from the first pico8 jam? I think zep created a thread on the bbs.

**Comment by felipebueno** [comment]
Good ideia, @booyaa :smiley: :+1: 
Can you make a pull request with this changes?

**Comment by felipebueno** [comment]
It's been a few months since I last checked Pico-8's forum.

@booyaa @marteaurouge @josefnpat any ideas on some really good (awesome?) carts to add to this list?
